--Up

-- account table
CREATE TABLE ACCOUNT(
ACCOUNT_ID TEXT PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD TEXT NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL,
BUSINESS_NAME VARCHAR(255) NOT NULL
);